# curl -X 'GET' 
#  'https://localhost:7070/Dta/cities/name/san%20rafael' 
#  -H 'accept: application/json'
GET https://localhost:7070/Dta/cities/name/san%20rafael
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:7070/Dta/districts/101' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/Dta/districts/508
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:7070/Dta/districts/1' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/Dta/cities/5
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:7070/Dta/Provinces' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/Dta/Provinces
Accept: application/json

###
